version: '3.4'

services:
  dhcpd:
    image: networkboot/dhcpd
    restart: unless-stopped
    build:
      context: .
      network: host
    container_name: dhcpdocker

    volumes:
      - ./data:/data

networks:
  dhcp_network:
    ipam:
      config:
        - subnet: 192.168.16.0/24
