version: '3.4'

services:
  dhcpd:
    build:
      context: .
    container_name: dhcpdocker
    network_mode: host
    networks:
      dhcp_network:
        ipv4_address: 192.168.16.2

    volumes:
      - ./data:/data

networks:
  dhcp_network:
    ipam:
      config:
        - subnet: 192.168.16.0/24