version: '3.3'

services:
  dhcpd:
    image: networkboot/dhcpd
    restart: unless-stopped
    args:                                                                      
      eth0
    volumes:
      - ./data:/data