version: '3.4'

services:
  dhcpd:
    build:
      context: .
      network: host
    contenair_name: dhcpdocker
    image: networkboot/dhcpd
    restart: unless-stopped

    volumes:
      - ./data:/data
